### ISSUE TITLE
Validating Shex requires to refresh the whole page

### ISSUE THREAD

**Issue by tonicebrian** [weso/rdfshape#34]
I've realised that the button validate in http://rdfshape.weso.es/shexValidate only works the first time the page loads.

**Steps to reproduce:**

- Fill code boxes with content from https://github.com/weso/simpleShExScala/tree/master/examples
- Click on Validate button
- A green box on top of the page appears telling that the RDF is valid
- Go to the RDF box and remove the snippet `; :age :unknown`
- Click on Validate again
- Still the green box can be seen on top

**Expected behaviour**
- Since we've removed a mandatory field for User an error message would be expected somewhere.

**Tested**
- Google Chrome 78.0.3904.108 (Official Build) (64-bit)
- MacOS Mojave

**Comment by ulitol97** [comment]
I believe the validator was working without the need of refreshing the page and this issue was due to a bad UI/messaging in the client as seen in [https://github.com/weso/rdfshape-client/pull/45](https://github.com/weso/rdfshape-client/pull/45).

As a counter example, you may reproduce the following steps:

- Navigate to https://rdfshape.weso.es/shexValidate
- Fill code boxes with content from https://github.com/weso/simpleShExScala/tree/master/examples
- Click on Validate button
- **A warning should appear because "age unknown" is not conformant and should be an integer.**
- Go to the RDF box and change the snippet `:age :unknown` to `:age 25`.
- Click on Validate again
- **A green box should appear because all nodes are valid and conformant.**
