### ISSUE TITLE
Check why tests are failing in Travis

### ISSUE THREAD

**Issue by labra** [weso/rdfshape#35]
It seems that some module has added coverage code that prevents the tests to be run in Travis. The error shown is:

```
[error] ## Exception when compiling 2 sources to /home/travis/build/weso/rdfshape/target/scala-2.13/classes
[error] java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
[error] com.github.ghik.silencer.SilencerPlugin.reporter$lzycompute(SilencerPlugin.scala:27)
[error] com.github.ghik.silencer.SilencerPlugin.com$github$ghik$silencer$SilencerPlugin$$reporter(SilencerPlugin.scala:26)
[error] com.github.ghik.silencer.SilencerPlugin.processOptions(SilencerPlugin.scala:50)
. . .
```

**Comment by ulitol97** [comment]
Closing this issue (outdated).

At the moment and after [https://github.com/weso/rdfshape/commit/0a1eddc969586a64861280d4774cf9da4ac036c2](https://github.com/weso/rdfshape/commit/0a1eddc969586a64861280d4774cf9da4ac036c2), tests are not failing in Travis, although builds still fail due to codecov (separate issue).
